services:
  - type: web
    name: aadarsh-coaching-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run chatbot.py --server.port $PORT"
    envVars:
      - key: API_KEY
        value: "rnd_DJRjJTqijqY1kqow6hXf7fSWrx8B"  # Replace with the actual API key
      - key: CHATBOT_NAME
        value: "Aadarsh Coaching Chatbot"
    autoDeploy: true